name: easy_hotel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-421.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  photo_view: ^0.14.0
  flutter_screenutil: ^5.6.0
  get_storage: ^2.0.3
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1
  url_launcher: ^6.1.7
  dio: ^4.0.6
  internet_connection_checker: ^1.0.0+1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

